GET http://localhost:3000/posts
Auth:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYmViYSIsImlhdCI6MTY0NDM5MjUyNH0.KpGiUuybmvE9hlxLOXZXaocC951PjcqW1HXTgVfpJeI





###


POST http://localhost:3000/login
Content-Type: application/json

{
    "username" : "beba"
}

